config/routes.rb
Rails.application.routes.draw do
  resources :newsletters
  root 'welcome#index'
  resources :gifts
  resources :activity_groups, path: '/activites'
  resources :activities, path: '/cours'
  resources :students
  resources :teachers

  ## STATIC PAGES
  get '/comment_ca_marche', to: 'welcome#comment_ca_marche'
  get '/faq', to: 'welcome#faq'
  get '/tarifs', to: 'welcome#tarifs'
  get '/galerie_des_profs', to: 'welcome#galerie_des_profs'
  get '/qui_sommes_nous', to: 'welcome#qui_sommes_nous'
  get '/qui_sont_les_professeurs', to: 'welcome#qui_sont_les_professeurs'
  get '/recrutements', to: 'welcome#recrutements'
  get '/vos_avantages', to: 'welcome#vos_avantages'
  get '/mentions-legales', to: 'welcome#mentions_legales'
  get '/contact', to: 'welcome#contact'
  get '/presse', to: 'welcome#presse'
  get '/testimonials', to: 'welcome#testimonials'

  ## COURS
  get '/cours-de-danse-de-couple', to: 'activity_groups#couple_danses'
  get '/cours-particulier-de-danse', to: 'activity_groups#autres_danses'

  match '/cours-de-rock' => 'activity_groups#show', :defaults => { :id => '1' }, via: [:get]
  match '/cours-de-danse-latino' => 'activity_groups#show', :defaults => { :id => '2' }, via: [:get]
  match '/cours-de-valse-et-salon' => 'activity_groups#show', :defaults => { :id => '3' }, via: [:get]
  match '/cours-de-tango-argentin' => 'activity_groups#show', :defaults => { :id => '4' }, via: [:get]
  match '/cours-de-danses-urbaines' => 'activity_groups#show', :defaults => { :id => '5' }, via: [:get]
  match '/cours-de-world-danse' => 'activity_groups#show', :defaults => { :id => '6' }, via: [:get]
  match '/cours-de-line-danse' => 'activity_groups#show', :defaults => { :id => '7' }, via: [:get]
  match '/cours-de-danse-traditionelle' => 'activity_groups#show', :defaults => { :id => '8' }, via: [:get]
  match '/cours-de-danse-classique' => 'activity_groups#show', :defaults => { :id => '9' }, via: [:get]

  match '/cours-de-yoga-pilates-gym' => 'activity_groups#show', :defaults => { :id => '10' }, via: [:get]
  match '/cours-de-yoga-dynamique' => 'activities#show', :defaults => { :id => '48' }, via: [:get]
  match '/cours-de-yoga-doux' => 'activities#show', :defaults => { :id => '49' }, via: [:get]
  match '/cours-de-yoga-grossesse' => 'activities#show', :defaults => { :id => '50' }, via: [:get]
  match '/cours-de-pilates' => 'activities#show', :defaults => { :id => '51' }, via: [:get]
  match '/cours-de-gym-douce' => 'activities#show', :defaults => { :id => '52' }, via: [:get]
  match '/cours-de-feldenkrais' => 'activities#show', :defaults => { :id => '53' }, via: [:get]
  match '/cours-de-qi-jong' => 'activities#show', :defaults => { :id => '54' }, via: [:get]
  match '/cours-de-tai-chi-chuan' => 'activities#show', :defaults => { :id => '55' }, via: [:get]
  match '/cours-de-gym-suédoise' => 'activities#show', :defaults => { :id => '56' }, via: [:get]
  match '/cours-de-zumba' => 'activities#show', :defaults => { :id => '57' }, via: [:get]

  match '/coaching-sportif' => 'activity_groups#show', :defaults => { :id => '11' }, via: [:get]
  match '/coaching-renforcement' => 'activities#show', :defaults => { :id => '58' }, via: [:get]
  match '/coaching-perte-de-poids' => 'activities#show', :defaults => { :id => '59' }, via: [:get]
  match '/coaching-cardio' => 'activities#show', :defaults => { :id => '60' }, via: [:get]
  match '/coaching-prisse-masse' => 'activities#show', :defaults => { :id => '61' }, via: [:get]
  match '/coaching-grossesse' => 'activities#show', :defaults => { :id => '62' }, via: [:get]
  match '/coaching-post-grossesse' => 'activities#show', :defaults => { :id => '63' }, via: [:get]
  match '/coaching-senior' => 'activities#show', :defaults => { :id => '64' }, via: [:get]
  match '/coaching-zumba' => 'activities#show', :defaults => { :id => '65' }, via: [:get]

  match '/cours-d-arts-martiaux' => 'activity_groups#show', :defaults => { :id => '12' }, via: [:get]
  match '/cours-de-boxe' => 'activities#show', :defaults => { :id => '66' }, via: [:get]
  match '/cours-de-boxe-thai' => 'activities#show', :defaults => { :id => '67' }, via: [:get]
  match '/cours-de-self-defense' => 'activities#show', :defaults => { :id => '68' }, via: [:get]
  match '/cours-de-krav-maga' => 'activities#show', :defaults => { :id => '69' }, via: [:get]
  match '/cours-de-lady-boxing' => 'activities#show', :defaults => { :id => '70' }, via: [:get]
  match '/cours-de-karate' => 'activities#show', :defaults => { :id => '71' }, via: [:get]
  match '/cours-de-capoeira' => 'activities#show', :defaults => { :id => '72' }, via: [:get]
  match '/cours-de-kung-fu' => 'activities#show', :defaults => { :id => '73' }, via: [:get]
  match '/cours-de-thai-chi-chuan' => 'activities#show', :defaults => { :id => '74' }, via: [:get]

  match '/cours-de-musique' => 'activity_groups#show', :defaults => { :id => '13' }, via: [:get]
  match '/cours-d-eveil-musical' => 'activities#show', :defaults => { :id => '75' }, via: [:get]
  match '/cours-de-solfege' => 'activities#show', :defaults => { :id => '76' }, via: [:get]
  match '/cours-de-guitare' => 'activities#show', :defaults => { :id => '77' }, via: [:get]
  match '/cours-de-guitare-electrique' => 'activities#show', :defaults => { :id => '78' }, via: [:get]
  match '/cours-de-piano' => 'activities#show', :defaults => { :id => '79' }, via: [:get]
  match '/cours-de-violon' => 'activities#show', :defaults => { :id => '80' }, via: [:get]
  match '/cours-de-percussion' => 'activities#show', :defaults => { :id => '81' }, via: [:get]
  match '/cours-de-batterie' => 'activities#show', :defaults => { :id => '82' }, via: [:get]
  match '/cours-de-flute' => 'activities#show', :defaults => { :id => '83' }, via: [:get]
  match '/cours-de-musique-autres' => 'activities#show', :defaults => { :id => '84' }, via: [:get]

  match '/cours-de-chant' => 'activity_groups#show', :defaults => { :id => '14' }, via: [:get]
  match '/cours-de-chant-pour-debutant' => 'activities#show', :defaults => { :id => '85' }, via: [:get]
  match '/cours-de-chant-pour-enfant' => 'activities#show', :defaults => { :id => '86' }, via: [:get]
  match '/cours-de-chant-lyrique' => 'activities#show', :defaults => { :id => '87' }, via: [:get]
  match '/cours-de-chant-pop-rock' => 'activities#show', :defaults => { :id => '88' }, via: [:get]
  match '/cours-de-chant-jazz-gospel' => 'activities#show', :defaults => { :id => '89' }, via: [:get]
  match '/cours-de-technique-vocale' => 'activities#show', :defaults => { :id => '90' }, via: [:get]
  match '/cours-d-interpretation-vocale' => 'activities#show', :defaults => { :id => '91' }, via: [:get]

  ## EVENEMENTS
  match '/cours-mariage' => 'activity_groups#show', :defaults => { :id => '15' }, via: [:get]
  match '/ouverture-de-bal-traditionelle' => 'activities#show', :defaults => { :id => '92' }, via: [:get]
  match '/ouverture-de-bal-moderne' => 'activities#show', :defaults => { :id => '93' }, via: [:get]
  match '/ouverture-de-bal-danse-a-deux' => 'activities#show', :defaults => { :id => '94' }, via: [:get]
  match '/ouverture-de-bal-dirty-dancing' => 'activities#show', :defaults => { :id => '95' }, via: [:get]
  match '/ouverture-de-bal-autres' => 'activities#show', :defaults => { :id => '96' }, via: [:get]
  match '/ouverture-de-bal-groupes' => 'activities#show', :defaults => { :id => '97' }, via: [:get]
  match '/EVJF-DANSE-EVG' => 'activities#show', :defaults => { :id => '98' }, via: [:get]

  match '/cours-danse-anniversaire' => 'activity_groups#show', :defaults => { :id => '16' }, via: [:get]
  match '/cours-de-danse-tete-a-tete' => 'activities#show', :defaults => { :id => '100' }, via: [:get]
  match '/animation-anniversaire' => 'activities#show', :defaults => { :id => '101' }, via: [:get]
  match '/cours-chant-anniversaire' => 'activities#show', :defaults => { :id => '102' }, via: [:get]
  match '/animation-anniversaire-enfant' => 'activities#show', :defaults => { :id => '103' }, via: [:get]

  match '/autres-evenements' => 'activity_groups#show', :defaults => { :id => '17' }, via: [:get]
  match '/bar-mitsva' => 'activities#show', :defaults => { :id => '104' }, via: [:get]
  match '/pot-de-depart' => 'activities#show', :defaults => { :id => '105' }, via: [:get]
  match '/cours-de-danse-rallye' => 'activities#show', :defaults => { :id => '106' }, via: [:get]
  match '/preparation-bal-de-vienne' => 'activities#show', :defaults => { :id => '107' }, via: [:get]
  match '/cours-prives-sur-mesure' => 'activities#show', :defaults => { :id => '108' }, via: [:get]
  match '/organisation-de-surprise' => 'activities#show', :defaults => { :id => '109' }, via: [:get]
  match '/cours-entre-amis' => 'activities#show', :defaults => { :id => '110' }, via: [:get]

  match '/cours-de-groupe' => 'activity_groups#show', :defaults => { :id => '18' }, via: [:get]
  match '/soiree-a-theme' => 'activities#show', :defaults => { :id => '111' }, via: [:get]
  match '/coaching-sportif-entre-amis' => 'activities#show', :defaults => { :id => '112' }, via: [:get]
  match '/flash-mob-personnalise' => 'activities#show', :defaults => { :id => '113' }, via: [:get]
  match '/evjf' => 'activities#show', :defaults => { :id => '114' }, via: [:get]

  match '/accompagnement-pro' => 'activity_groups#show', :defaults => { :id => '19' }, via: [:get]
  match '/preparation-sportive' => 'activities#show', :defaults => { :id => '115' }, via: [:get]
  match '/preparation-examen' => 'activities#show', :defaults => { :id => '116' }, via: [:get]
  match '/accompagnement' => 'activities#show', :defaults => { :id => '117' }, via: [:get]
  match '/spectacle-de-danse' => 'activities#show', :defaults => { :id => '118' }, via: [:get]
  match '/spectacle-de-chant' => 'activities#show', :defaults => { :id => '119' }, via: [:get]
  match '/spectacle-de-musique' => 'activities#show', :defaults => { :id => '120' }, via: [:get]
  match '/sur-mesure' => 'activities#show', :defaults => { :id => '121' }, via: [:get]

app/models/activity_group.rb
class ActivityGroup < ActiveRecord::Base
  has_many :activities
  
  # extend FriendlyId
  # friendly_id :url_name, use: :slugged
end

app/controllers/activity_groups_controller.rb
class ActivityGroupsController < ApplicationController
  before_action :set_activity_group, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:index, :show, :edit, :update, :destroy]

  # GET /activity_groups
  # GET /activity_groups.json
  def index
    @activity_groups = ActivityGroup.all
  end

  # GET /activity_groups/1
  # GET /activity_groups/1.json
  def show
  end

  def couple_danses
    @activity_groups = ActivityGroup.first(4)
  end

  def autres_danses
     @activity_groups = ActivityGroup.limit(5).offset(2)
  end

  # GET /activity_groups/new
  def new
    @activity_group = ActivityGroup.new
  end

  # GET /activity_groups/1/edit
  def edit
  end

  # POST /activity_groups
  # POST /activity_groups.json
  def create
    @activity_group = ActivityGroup.new(activity_group_params)

    respond_to do |format|
      if @activity_group.save
        format.html { redirect_to @activity_group, notice: 'Activity group was successfully created.' }
        format.json { render :show, status: :created, location: @activity_group }
      else
        format.html { render :new }
        format.json { render json: @activity_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_groups/1
  # PATCH/PUT /activity_groups/1.json
  def update
    respond_to do |format|
      if @activity_group.update(activity_group_params)
        format.html { redirect_to @activity_group, notice: 'Activity group was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_group }
      else
        format.html { render :edit }
        format.json { render json: @activity_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_groups/1
  # DELETE /activity_groups/1.json
  def destroy
    @activity_group.destroy
    respond_to do |format|
      format.html { redirect_to activity_groups_url, notice: 'Activity group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_group
      @activity_group = ActivityGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_group_params
      params.require(:activity_group).permit({:activity_ids => []}, :activities, :description, :name, :picture, :main_picture, :carousel_price)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_USER'] && password == ENV['HTTP_PASSWORD']
      end
    end
end

app/helpers/activity_groups_helper.rb
module ActivityGroupsHelper
end

app/views/activity_groups/_form.html.erb
<%= form_for(@activity_group) do |f| %>
  <% if @activity_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_group.errors.count, "error") %> prohibited this activity_group from being saved:</h2>

      <ul>
      <% @activity_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="field">
        <%= f.text_field :name, placeholder: 'Nom de Famille de Activités (ex. Salsa & danses latinos)' %>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="field">
        <%= f.text_field :description, placeholder: 'Description de cette Famille de Activités (ex. Le rock n roll viens des Etats Unis. Elvis Presley est la star.)' %>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="field">
        <%= f.text_field :carousel_price, placeholder: 'Prix (sur Home Carousel)' %>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="field">
        <%= f.text_field :picture, placeholder: 'Ajouter une image qui represent cette Famille.' %>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="field">
        <%= f.text_field :main_picture, placeholder: 'Ajouter une image background pour cette Famille.' %>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-lg-12">
      <div class="actions">
        <%= f.submit 'Créer' %>
      </div>
    </div>
  </div>
<% end %>

app/views/activity_groups/autres_danses.html.erb
<style media="screen">
  #image-div { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url('https://s3.eu-central-1.amazonaws.com/rails-demo-production-coursparticuliers/AUTRES+DANSE+FAMILY_opt.jpg'); }
  #activity-group-main-container { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url('https://s3.eu-central-1.amazonaws.com/rails-demo-production-coursparticuliers/AUTRES+DANSE+FAMILY_opt.jpg'); }
</style>
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Autres danses</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <div class="col-lg-5">
          <p>Envie de nouvelles sensations??? Apprenez à danser grâce aux nouveaux cours particuliers. Découvrze ici toutes les danses "solo" et maitrisez votre corps avec l'apprentissage de nouveaux mouvements. Danse Classique, Danse contemporaine ou bien danse du monde traditionelle ou moderne? Laquelle vous tente le plus??</p>
        </div>
        <div class="col-lg-7">
          <div class="row">
            <% @activity_groups.each do |a| %>
              <div class="col-lg-2" id="image-div" style="border:1px solid black;margin:1em;padding:2.5em 1em 1em 1em;height:200px;width:200px;color:#f20661;">
                <%= link_to a.name, a %><br>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row" style="margin:2em 0;">
        <div class="col-lg-12">
          <a href="/students/new" id="activity-button">Je fais ma demande</a>
        </div>
      </div>
      <div class="row">
        <%= link_to 'Back', root_path %>
      </div>
      
    </div>
  </div>
</div>

app/views/activity_groups/couple_danses.html.erb
<style media="screen">
  #image-div { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url('https://s3.eu-central-1.amazonaws.com/rails-demo-production-coursparticuliers/DANSE+DE+COUPLE+FAMILY_opt.jpg'); }
  #activity-group-main-container { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url('https://s3.eu-central-1.amazonaws.com/rails-demo-production-coursparticuliers/DANSE+DE+COUPLE+FAMILY_opt.jpg'); }
</style>
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Danse de couple</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <div class="col-lg-5">
          <p>Voyagez aux quatres coins du monde grâce aux danses de couple! De l'amérique latine à l'Autriche, en passant par les Etats-Unis, les Caraîbes et même l'Angola, chaque pays a, à sa manière contribué au développement des danses de couple. Grâce à nos professeurs et à nos cours particuleirs de danse, apprenez rapidement une ou plusieurs danses afin de  briller sur la piste dés votre prochaines soirées.</p>
        </div>
        <div class="col-lg-7">
          <div class="row">
            <% @activity_groups.each do |a| %>
              <div class="col-lg-2" id="image-div" style="border:1px solid black;margin:1em;padding:2.5em 1em 1em 1em;height:200px;width:200px;color:#f20661;">
                <%= link_to a.name, a %><br>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row" style="margin:2em 0;">
        <div class="col-lg-12">
          <a href="/students/new" id="activity-button">Je fais ma demande</a>
        </div>
      </div>
      <div class="row">
        <%= link_to 'Back', root_path %>
      </div>
      
    </div>
  </div>
</div>

app/views/activity_groups/edit.html.erb
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Modifié une Famille de Activités</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center" id="header-title">
        <%= render 'form' %>

        <%= link_to 'Show', @activity_group %> |
        <%= link_to 'Back', activity_groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/activity_groups/index.html.erb
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Listing Activity Groups</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12" id="header-title">
        <table>
          <thead>
            <tr>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @activity_groups.each do |activity_group| %>
              <tr>
                <td><%= activity_group.name %></td>
                <td><%= activity_group.id %></td>
                <td><%= link_to 'Show', activity_group %></td>
                <td><%= link_to 'Edit', edit_activity_group_path(activity_group) %></td>
                <td><%= link_to 'Destroy', activity_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'New Activity group', new_activity_group_path %>
      </div>
    </div>
  </div>
</div>

app/views/activity_groups/new.html.erb
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Nouvelle Famille de Activités</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center" id="header-title">
        <%= render 'form' %>
        <%= link_to 'Back', activity_groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/activity_groups/show.html.erb
<style media="screen">
  #image-div { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url(<%= @activity_group.picture %>); }
  #activity-group-main-container { background-image: linear-gradient(
      rgba(0, 0, 0, 0.4),
      rgba(0, 0, 0, 0.4)
    ), url(<%= @activity_group.main_picture %>); }
</style>
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1><%= @activity_group.name %></h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <div class="col-lg-5">
          <%= @activity_group.description %>
        </div>
        <div class="col-lg-7">
          <div class="row">
            <% @activity_group.activities.each do |a| %>
              <div class="col-lg-2" id="image-div" style="border:1px solid black;margin:1em;padding:2.5em 1em 1em 1em;height:200px;width:200px;color:#f20661;">
                <%= link_to a.name, a %><br>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row" style="margin:2em 0;">
        <div class="col-lg-12">
          <a href="/students/new" id="activity-button">Devis personnalisé & réservation</a>
          <p id="disclaimer">* « Les Nouveaux Cours Particuliers SAS » est une structure déclarée service à la personne auprès le DIRRECTE Paris sous le numéro SAP 811071893. Vous bénéficiez en conséquence des avantages fiscaux relatifs aux service à la personne, à savoir une réduction/crédit d’impôt de 50% des montants engagés. Nous prenons en charge l’ensemble des démarches administratives. L’avantage fiscal est valable pour les cours  dispensés à domicile de manière individuelle ou dans le cadre familial. Tarif après réduction fiscale. </p>
          <%= image_tag('services_a_la_personne.png', :alt => "Image", :class => "logo-sap") %>
        </div>
      </div>
      <div class="row">
        <%= link_to 'Back', root_path %>
      </div>
      
    </div>
  </div>
</div>