config/routes.rb
Rails.application.routes.draw do
  resources :newsletters
  root 'welcome#index'
  resources :gifts
  resources :activity_groups, path: '/activites'
  resources :activities, path: '/cours'
  resources :students
  resources :teachers

  ## STATIC PAGES
  get '/comment_ca_marche', to: 'welcome#comment_ca_marche'
  get '/faq', to: 'welcome#faq'
  get '/tarifs', to: 'welcome#tarifs'
  get '/galerie_des_profs', to: 'welcome#galerie_des_profs'
  get '/qui_sommes_nous', to: 'welcome#qui_sommes_nous'
  get '/qui_sont_les_professeurs', to: 'welcome#qui_sont_les_professeurs'
  get '/recrutements', to: 'welcome#recrutements'
  get '/vos_avantages', to: 'welcome#vos_avantages'
  get '/mentions-legales', to: 'welcome#mentions_legales'
  get '/contact', to: 'welcome#contact'
  get '/presse', to: 'welcome#presse'
  get '/testimonials', to: 'welcome#testimonials'

  ## COURS
  get '/cours-de-danse-de-couple', to: 'activity_groups#couple_danses'
  get '/cours-particulier-de-danse', to: 'activity_groups#autres_danses'

  match '/cours-de-rock' => 'activity_groups#show', :defaults => { :id => '1' }, via: [:get]
  match '/cours-de-danse-latino' => 'activity_groups#show', :defaults => { :id => '2' }, via: [:get]
  match '/cours-de-valse-et-salon' => 'activity_groups#show', :defaults => { :id => '3' }, via: [:get]
  match '/cours-de-tango-argentin' => 'activity_groups#show', :defaults => { :id => '4' }, via: [:get]
  match '/cours-de-danses-urbaines' => 'activity_groups#show', :defaults => { :id => '5' }, via: [:get]
  match '/cours-de-world-danse' => 'activity_groups#show', :defaults => { :id => '6' }, via: [:get]
  match '/cours-de-line-danse' => 'activity_groups#show', :defaults => { :id => '7' }, via: [:get]
  match '/cours-de-danse-traditionelle' => 'activity_groups#show', :defaults => { :id => '8' }, via: [:get]
  match '/cours-de-danse-classique' => 'activity_groups#show', :defaults => { :id => '9' }, via: [:get]

  match '/cours-de-yoga-pilates-gym' => 'activity_groups#show', :defaults => { :id => '10' }, via: [:get]
  match '/cours-de-yoga-dynamique' => 'activities#show', :defaults => { :id => '48' }, via: [:get]
  match '/cours-de-yoga-doux' => 'activities#show', :defaults => { :id => '49' }, via: [:get]
  match '/cours-de-yoga-grossesse' => 'activities#show', :defaults => { :id => '50' }, via: [:get]
  match '/cours-de-pilates' => 'activities#show', :defaults => { :id => '51' }, via: [:get]
  match '/cours-de-gym-douce' => 'activities#show', :defaults => { :id => '52' }, via: [:get]
  match '/cours-de-feldenkrais' => 'activities#show', :defaults => { :id => '53' }, via: [:get]
  match '/cours-de-qi-jong' => 'activities#show', :defaults => { :id => '54' }, via: [:get]
  match '/cours-de-tai-chi-chuan' => 'activities#show', :defaults => { :id => '55' }, via: [:get]
  match '/cours-de-gym-suédoise' => 'activities#show', :defaults => { :id => '56' }, via: [:get]
  match '/cours-de-zumba' => 'activities#show', :defaults => { :id => '57' }, via: [:get]

  match '/coaching-sportif' => 'activity_groups#show', :defaults => { :id => '11' }, via: [:get]
  match '/coaching-renforcement' => 'activities#show', :defaults => { :id => '58' }, via: [:get]
  match '/coaching-perte-de-poids' => 'activities#show', :defaults => { :id => '59' }, via: [:get]
  match '/coaching-cardio' => 'activities#show', :defaults => { :id => '60' }, via: [:get]
  match '/coaching-prisse-masse' => 'activities#show', :defaults => { :id => '61' }, via: [:get]
  match '/coaching-grossesse' => 'activities#show', :defaults => { :id => '62' }, via: [:get]
  match '/coaching-post-grossesse' => 'activities#show', :defaults => { :id => '63' }, via: [:get]
  match '/coaching-senior' => 'activities#show', :defaults => { :id => '64' }, via: [:get]
  match '/coaching-zumba' => 'activities#show', :defaults => { :id => '65' }, via: [:get]

  match '/cours-d-arts-martiaux' => 'activity_groups#show', :defaults => { :id => '12' }, via: [:get]
  match '/cours-de-boxe' => 'activities#show', :defaults => { :id => '66' }, via: [:get]
  match '/cours-de-boxe-thai' => 'activities#show', :defaults => { :id => '67' }, via: [:get]
  match '/cours-de-self-defense' => 'activities#show', :defaults => { :id => '68' }, via: [:get]
  match '/cours-de-krav-maga' => 'activities#show', :defaults => { :id => '69' }, via: [:get]
  match '/cours-de-lady-boxing' => 'activities#show', :defaults => { :id => '70' }, via: [:get]
  match '/cours-de-karate' => 'activities#show', :defaults => { :id => '71' }, via: [:get]
  match '/cours-de-capoeira' => 'activities#show', :defaults => { :id => '72' }, via: [:get]
  match '/cours-de-kung-fu' => 'activities#show', :defaults => { :id => '73' }, via: [:get]
  match '/cours-de-thai-chi-chuan' => 'activities#show', :defaults => { :id => '74' }, via: [:get]

  match '/cours-de-musique' => 'activity_groups#show', :defaults => { :id => '13' }, via: [:get]
  match '/cours-d-eveil-musical' => 'activities#show', :defaults => { :id => '75' }, via: [:get]
  match '/cours-de-solfege' => 'activities#show', :defaults => { :id => '76' }, via: [:get]
  match '/cours-de-guitare' => 'activities#show', :defaults => { :id => '77' }, via: [:get]
  match '/cours-de-guitare-electrique' => 'activities#show', :defaults => { :id => '78' }, via: [:get]
  match '/cours-de-piano' => 'activities#show', :defaults => { :id => '79' }, via: [:get]
  match '/cours-de-violon' => 'activities#show', :defaults => { :id => '80' }, via: [:get]
  match '/cours-de-percussion' => 'activities#show', :defaults => { :id => '81' }, via: [:get]
  match '/cours-de-batterie' => 'activities#show', :defaults => { :id => '82' }, via: [:get]
  match '/cours-de-flute' => 'activities#show', :defaults => { :id => '83' }, via: [:get]
  match '/cours-de-musique-autres' => 'activities#show', :defaults => { :id => '84' }, via: [:get]

  match '/cours-de-chant' => 'activity_groups#show', :defaults => { :id => '14' }, via: [:get]
  match '/cours-de-chant-pour-debutant' => 'activities#show', :defaults => { :id => '85' }, via: [:get]
  match '/cours-de-chant-pour-enfant' => 'activities#show', :defaults => { :id => '86' }, via: [:get]
  match '/cours-de-chant-lyrique' => 'activities#show', :defaults => { :id => '87' }, via: [:get]
  match '/cours-de-chant-pop-rock' => 'activities#show', :defaults => { :id => '88' }, via: [:get]
  match '/cours-de-chant-jazz-gospel' => 'activities#show', :defaults => { :id => '89' }, via: [:get]
  match '/cours-de-technique-vocale' => 'activities#show', :defaults => { :id => '90' }, via: [:get]
  match '/cours-d-interpretation-vocale' => 'activities#show', :defaults => { :id => '91' }, via: [:get]

  ## EVENEMENTS
  match '/cours-mariage' => 'activity_groups#show', :defaults => { :id => '15' }, via: [:get]
  match '/ouverture-de-bal-traditionelle' => 'activities#show', :defaults => { :id => '92' }, via: [:get]
  match '/ouverture-de-bal-moderne' => 'activities#show', :defaults => { :id => '93' }, via: [:get]
  match '/ouverture-de-bal-danse-a-deux' => 'activities#show', :defaults => { :id => '94' }, via: [:get]
  match '/ouverture-de-bal-dirty-dancing' => 'activities#show', :defaults => { :id => '95' }, via: [:get]
  match '/ouverture-de-bal-autres' => 'activities#show', :defaults => { :id => '96' }, via: [:get]
  match '/ouverture-de-bal-groupes' => 'activities#show', :defaults => { :id => '97' }, via: [:get]
  match '/EVJF-DANSE-EVG' => 'activities#show', :defaults => { :id => '98' }, via: [:get]

  match '/cours-danse-anniversaire' => 'activity_groups#show', :defaults => { :id => '16' }, via: [:get]
  match '/cours-de-danse-tete-a-tete' => 'activities#show', :defaults => { :id => '100' }, via: [:get]
  match '/animation-anniversaire' => 'activities#show', :defaults => { :id => '101' }, via: [:get]
  match '/cours-chant-anniversaire' => 'activities#show', :defaults => { :id => '102' }, via: [:get]
  match '/animation-anniversaire-enfant' => 'activities#show', :defaults => { :id => '103' }, via: [:get]

  match '/autres-evenements' => 'activity_groups#show', :defaults => { :id => '17' }, via: [:get]
  match '/bar-mitsva' => 'activities#show', :defaults => { :id => '104' }, via: [:get]
  match '/pot-de-depart' => 'activities#show', :defaults => { :id => '105' }, via: [:get]
  match '/cours-de-danse-rallye' => 'activities#show', :defaults => { :id => '106' }, via: [:get]
  match '/preparation-bal-de-vienne' => 'activities#show', :defaults => { :id => '107' }, via: [:get]
  match '/cours-prives-sur-mesure' => 'activities#show', :defaults => { :id => '108' }, via: [:get]
  match '/organisation-de-surprise' => 'activities#show', :defaults => { :id => '109' }, via: [:get]
  match '/cours-entre-amis' => 'activities#show', :defaults => { :id => '110' }, via: [:get]

  match '/cours-de-groupe' => 'activity_groups#show', :defaults => { :id => '18' }, via: [:get]
  match '/soiree-a-theme' => 'activities#show', :defaults => { :id => '111' }, via: [:get]
  match '/coaching-sportif-entre-amis' => 'activities#show', :defaults => { :id => '112' }, via: [:get]
  match '/flash-mob-personnalise' => 'activities#show', :defaults => { :id => '113' }, via: [:get]
  match '/evjf' => 'activities#show', :defaults => { :id => '114' }, via: [:get]

  match '/accompagnement-pro' => 'activity_groups#show', :defaults => { :id => '19' }, via: [:get]
  match '/preparation-sportive' => 'activities#show', :defaults => { :id => '115' }, via: [:get]
  match '/preparation-examen' => 'activities#show', :defaults => { :id => '116' }, via: [:get]
  match '/accompagnement' => 'activities#show', :defaults => { :id => '117' }, via: [:get]
  match '/spectacle-de-danse' => 'activities#show', :defaults => { :id => '118' }, via: [:get]
  match '/spectacle-de-chant' => 'activities#show', :defaults => { :id => '119' }, via: [:get]
  match '/spectacle-de-musique' => 'activities#show', :defaults => { :id => '120' }, via: [:get]
  match '/sur-mesure' => 'activities#show', :defaults => { :id => '121' }, via: [:get]

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:index, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :email, :phone_number, :description, :avatar, :last_name,:civil_status,:date_of_birth,:nationality,:activity_group_1,:activity_group_2,:activity_group_3,:activity_1,:activity_1_level,:activity_2, :activity_2_level,:activity_3,:activity_3_level,:start_date,:availability,:diploma,:teaching_area_1,:teaching_area_1_perimeter,:teaching_area_2,:teaching_area_2_perimeter,:teaching_area_3,:teaching_area_3_perimeter,:has_a_vehicle,:city,:postal_code,:address,:address_compliment,:country,)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_USER'] && password == ENV['HTTP_PASSWORD']
      end
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<div class="container-fluid" id="teacher-header-container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1>Edit Professeur</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="new-teacher-container">
  <div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
      <p>Modifier votre profile !</p><br><br>
      <%= render 'form' %>
      <%= link_to 'Back', teachers_path %>
    </div>
    <div class="col-lg-2">

    </div>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Listing Teachers</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12" id="header-title">
        <table>
          <thead>
            <tr>
              <th>Civil status</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Email</th>
              <th>Phone</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @teachers.each do |teacher| %>
              <tr>
                <td><%= teacher.civil_status %></td>
                <td><%= teacher.first_name %></td>
                <td><%= teacher.last_name %></td>
                <td><%= teacher.email %></td>
                <td><%= teacher.phone_number %></td>
                <td><%= link_to 'Show', teacher %></td>
                <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
                <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'New Teacher', new_teacher_path %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="container-fluid" id="teacher-header-container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1>Professeurs</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="new-teacher-container">
  <div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
      <p>L’équipe des Nouveaux Cours Particuliers est très heureuse de vous accueillir !</p>
      <p>Vous trouverez ci-joint votre dossier d’inscription.</p>
      <p>Il est réservé à un usage interne et nous permet de recueillir l’ensemble des informations nécessaires à la gestion quotidienne de votre future activité, et d’être en conformité avec la législation.</p>
      <p>Je vous remercie par avance de bien vouloir le remplir.</p>
      <p>Je reste disponible pour toute question et vous souhaite la bienvenue parmi les agitateurs de domicile.</p>
      <%= render 'form' %>
      <%= link_to 'Back', teachers_path %>
    </div>
    <div class="col-lg-2">

    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="container-fluid" id="activity-group-header-container">
  <div class="row">
    <div class="col-lg-12 text-center" id="header-title">
      <h1>Teacher profile</h1>
    </div>
  </div>
</div>
<div class="container-fluid" id="activity-group-main-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12" id="header-title">
        <table>

          <tbody>
            <tr>
              <td style="font-weight:900;">Civil status</td>
              <td><%= @teacher.civil_status %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">First name</td>
              <td><%= @teacher.first_name %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Last name</td>
              <td><%= @teacher.last_name %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Email</td>
              <td><%= @teacher.email %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Phone number</td>
              <td><%= @teacher.phone_number %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Date of birth</td>
              <td><%= @teacher.date_of_birth %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Nationality</td>
              <td><%= @teacher.nationality %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Address</td>
              <td><%= @teacher.address %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Address compliment</td>
              <td><%= @teacher.address_compliment %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Country</td>
              <td><%= @teacher.country %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Postal code</td>
              <td><%= @teacher.postal_code %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Diploma</td>
              <td><%= @teacher.diploma %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity group #1</td>
              <td><%= @teacher.activity_group_1 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity group #2</td>
              <td><%= @teacher.activity_group_2 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity group #3</td>
              <td><%= @teacher.activity_group_3 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #1</td>
              <td><%= @teacher.activity_1 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #1 (level)</td>
              <td><%= @teacher.activity_1_level %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #2</td>
              <td><%= @teacher.activity_2 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #2 (level)</td>
              <td><%= @teacher.activity_2_level %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #3</td>
              <td><%= @teacher.activity_3 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Activity #3 (level)</td>
              <td><%= @teacher.activity_3_level %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Start date</td>
              <td><%= @teacher.start_date %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Availability</td>
              <td><%= @teacher.availability %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #1</td>
              <td><%= @teacher.teaching_area_1 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #1 (perimeter)</td>
              <td><%= @teacher.teaching_area_1_perimeter %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #2</td>
              <td><%= @teacher.teaching_area_2 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #2 (perimeter)</td>
              <td><%= @teacher.teaching_area_2_perimeter %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #3</td>
              <td><%= @teacher.teaching_area_3 %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Teaching area #3 (perimeter)</td>
              <td><%= @teacher.teaching_area_3_perimeter %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Has a vehicle</td>
              <td><%= @teacher.has_a_vehicle %></td>
            </tr>
            <tr>
              <td style="font-weight:900;">Description</td>
              <td><%= @teacher.description %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= link_to 'Edit', edit_teacher_path(@teacher) %> |
        <%= link_to 'Back', teachers_path %>
      </div>
    </div>
  </div>
</div>